# Generated by Django 5.1.1 on 2024-09-17 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etenderuzex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('tender_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=400)),
                ('display_number', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('1', 'Tender'), ('2', 'Auction')], max_length=50)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('clarific_date', models.DateTimeField(blank=True, null=True)),
                ('cost', models.FloatField()),
                ('currency', models.CharField(choices=[('106', 'UZS'), ('14', 'USD'), ('15', 'EUR'), ('20', 'RUB')], max_length=50)),
                ('seller_name', models.CharField(blank=True, max_length=100, null=True)),
                ('seller_tin', models.CharField(blank=True, max_length=50, null=True)),
                ('regin_name', models.CharField(blank=True, max_length=100, null=True)),
                ('district_name', models.CharField(blank=True, max_length=100, null=True)),
                ('seller_id', models.IntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='etenderuzex.category')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='etenderuzex.product')),
            ],
            options={
                'verbose_name_plural': 'Tenders',
            },
        ),
    ]
