# Generated by Django 5.1.1 on 2024-09-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etenderuzex', '0002_tender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tender',
            old_name='regin_name',
            new_name='region_name',
        ),
        migrations.AddField(
            model_name='tender',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
