# Generated by Django 5.1.1 on 2024-09-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etenderuzex', '0003_rename_regin_name_tender_region_name_tender_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckedTender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tender_id', models.IntegerField()),
                ('category_id', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Checked tenders',
            },
        ),
    ]
