# Generated by Django 5.1.1 on 2024-09-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etenderuzex', '0004_checkedtender'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tender',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='category_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='tender',
            name='tender_id',
            field=models.IntegerField(unique=True),
        ),
    ]
