# Generated by Django 5.1.1 on 2024-09-18 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etenderuzex', '0005_category_id_product_id_tender_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tender',
            name='product',
        ),
        migrations.CreateModel(
            name='TenderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etenderuzex.product')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etenderuzex.tender')),
            ],
            options={
                'verbose_name_plural': 'Tender products',
            },
        ),
    ]
