# Generated by Django 5.1.1 on 2024-09-18 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etenderuzex', '0006_remove_tender_product_tenderproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenderproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='etenderuzex.product'),
        ),
    ]
