# Generated by Django 5.1.1 on 2024-09-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etenderuzex', '0007_alter_tenderproduct_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkedtender',
            name='tender_id',
            field=models.IntegerField(unique=True),
        ),
    ]
