# Generated by Django 5.1.1 on 2024-09-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etenderuzex', '0008_alter_checkedtender_tender_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Telegram users',
            },
        ),
    ]
