name: Deploy Django Project

on:
  push:
    branches:
      - main  # Change to your default branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # Specify Python 3.11

      - name: Install dependencies
        run: |
          cd /home/Etender_back/
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install sshpass
        run: sudo apt-get install sshpass

      - name: Deploy to Server
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
        run: |
          echo "${SERVER_PASSWORD}" | sshpass ssh -o StrictHostKeyChecking=no ${SERVER_USER}@${SERVER_IP} << 'EOF'
            cd /path/to/your/project
            git pull origin main  # Ensure this matches your branch
            source /path/to/your/venv/bin/activate  # Activate your virtual environment
            pip install -r requirements.txt
            python manage.py migrate
            python manage.py collectstatic --noinput
            sudo systemctl restart gunicorn  # Adjust as necessary for your WSGI server
          EOF
