name: Deploy Django Project

on:
  push:
    branches:
      - main  # Change to your default branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # Specify Python 3.11

      - name: Deploy to Server
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
        run: |
          sshpass -p $SERVER_PASSWORD ssh -o StrictHostKeyChecking=no -t $SERVER_USER@$SERVER_IP << EOF
            cd /home/Etender_back/
            git pull origin main
            /home/Etender_back/venv/bin/pip3 install -r requirements.txt
            /home/Etender_back/venv/bin/python3 manage.py migrate
            /home/Etender_back/venv/bin/python3 manage.py collectstatic --noinput
            sudo supervisorctl restart etender
          EOF
